// export { default as LayoutMain } from './AppMain.vue'
export { default as LayoutMain } from './main/index.vue'
export { default as LayoutHeader } from './header/index.vue'
export { default as LayoutNavbar } from './navbar/index.vue'
export { default as LayoutSidebar } from './sidebar/index.vue'
export { default as LayoutFooter } from './footer/index.vue'
